using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LC_Save_Editor
{
    public enum VanillaShipUpgrades
    {
        OrangeSuit = 0,
        GreenSuit = 1,
        HazardSuit = 2,
        PajamaSuit = 3,
        CozyLights = 4,
        Teleporter = 5,
        Television = 6,
        Cupboard = 7,
        FileCabinet = 8,
        Toliet = 9,
        Shower = 10,
        LightSwitch = 11,
        RecordPlayer = 12,
        Table = 13,
        RomanticTable = 14,
        Bunkbed = 15,
        Terminal = 16,
        SignalTranslator = 17,
        LoudHorn = 18,
        InverseTeleporter = 19,
        JackoLantern = 20,
        WelcomeMat = 21,
        Goldfish = 22,
        PlushieMan = 23,
    }
    public enum VanillaItems
    {
        Binoculars = 0,
        BoomBox = 1,
        Flashlight = 3,
        Jetpack = 4,
        Key = 5,
        Lockpick = 6,
        Apparatus = 7,
        HandheldMonitor = 8,
        ProFlashlight = 9,
        Shovel = 10,
        Flashbang = 11,
        ExtensionLadder = 12,
        TzpInhalant = 13,
        WalkieTalkie = 14,
        StunGun = 15,
        Magic7Ball = 16,
        AirHorn = 17,
        Bell = 18,
        BigBolt = 19,
        Bottles = 20,
        Hairbrush = 21,
        Candy = 22,
        CashRegister = 23,
        ChemicalJug = 2,
        ClownHorn = 25,
        LargeAxel = 26,
        Teeth = 27,
        Dustpan = 28,
        EggBeater = 29,
        VTypeEngine = 30,
        GoldenCup = 31,
        Lamp = 32,
        Painting = 33,
        PlasticFish = 34,
        LaserPointer = 35,
        GoldBar = 36,
        Hairdryer = 37,
        MagnifyingGlass = 38,
        TatteredMetalSheet = 39,
        CookieMoldPan = 40,
        CoffeeMug = 41,
        PerfumeBottle = 42,
        OldPhone = 43,
        JarOfPickles = 44,
        PillBottle = 45,
        Ring = 47,
        RobotToy = 48,
        RubberDucky = 49,
        RedSoda = 50,
        SteeringWheel = 51,
        StopSign = 52,
        TeaKettle = 53,
        ToothPaste = 54,
        ToyCube = 55,
        BeeHive = 56,
        RadarBooster = 57,
        YieldSign = 58,
        Shotgun = 59,
        ShotgunShell = 60,
        SprayPaint = 61,
        HomemadeFlashbang = 62,
        GiftBox = 63,
        Flask = 64,
        Tragedy = 65,
        Comedy = 66,
        WhoopieCushion = 67
    }
    public enum VanillaMoons
    {
        Experimentation = 0,
        Assurance = 1,
        Vow = 2,
        CompanyBuilding = 3,
        March = 4,
        Rend = 5,
        Dine = 6,
        Offense = 7,
        Titan = 8
    }
    public enum VanillaEnemies
    {
        BaboonHawk,
        Blob,
        Centipede,
        Crawler,
        DocileLocustBees,
        Doublewing,
        RedLocustBees,
        DressGirl,
        Flowerman,
        ForestGiant,
        HoarderBug,
        Jester,
        LassoMan,
        MaskedPlayerEnemy,
        MouthDog,
        Nutcracker,
        Puffer,
        RedPillEnemyType,
        SandSpider,
        SandWorm,
        SpringMan

    }
    public enum VanillaStoryLogs
    {
        AssuranceLog = 1,
        ExperimentationLog = 2,
        ExperimentationLog2 = 3,
        TheCompanyLog = 4,
        MarchLog = 5,
        VowLog = 6,
        RendLog = 7,
        RendLog2 = 8,
        RendLog3 = 9,
        unknown1 = 10,
        unknown2 = 11,
        unknown3 = 12

    }

    public enum VanillaBestiary
    {
        SnareFlea = 0,
        Bracken = 1,
        Thumper = 2,
        EyelessDog = 3,
        HoardingBug = 4,
        Hygrodere = 5,
        ForestKeeper = 6,
        CoilHead = 7,
        LassoMan = 8,
        EarthLeviathan = 9,
        Jester = 10,
        SporeLizard = 11,
        BunkerSpider = 12,
        Manticoil = 13,
        CircuitBee = 14,
        RoamingLocust = 15,
        BaboonHawk = 16,
        Nutcracker = 17
    }
}
